version: "3"

services:

  app:
    build: .
    container_name: devops-app
    expose:
      - "5000"

  nginx:
    image: nginx:latest
    container_name: devops-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
